export const sidebar = [
    {
        'id':1,
        'name':'系统',
        'grounp':'system',
        'code':'system',
        'sub':[
            {
                'id':11,
                'name':'APP基本设置',
                'grounp':'system',
                'code':'setting',
            },
            {
                'id':12,
                'name':'BANNER管理',
                'grounp':'system',
                'code':'banner',
            },

        ]
    },
    {
        'id':2,
        'name':'商品',
        'grounp':'product',
        'code':'product',
        'sub':[
            {
                'id':21,
                'name':'商品分类',
                'grounp':'product',
                'code':'category',
            },
            {
                'id':22,
                'name':'商品列表',
                'grounp':'product',
                'code':'product',
            },
            {
                'id':22,
                'name':'订单',
                'grounp':'product',
                'code':'order',
            },

        ]
    },
    {
        'id':3,
        'name':'日程活动',
        'grounp':'schedule',
        'code':'schedule',
        'sub':[
            {
                'id':31,
                'name':'日程管理',
                'grounp':'schedule',
                'code':'schedule',
            },
            {
                'id':32,
                'name':'活动管理',
                'grounp':'schedule',
                'code':'activity',
            },
            {
                'id':32,
                'name':'优惠券管理',
                'grounp':'schedule',
                'code':'coupon',
            }
        ]
    },
    {
        'id':4,
        'name':'会员管理',
        'grounp':'user',
        'code':'user',
        'sub':[
            {
                'id':41,
                'name':'会员列表',
                'grounp':'user',
                'code':'user',
            },

        ]
    },
]

